# These configurations will be used
# unless explicitly overwritten by prompt specific
# settings

model: gemini-1.5-flash

json_mode: FALSE

temperature: 0.0

# If TRUE generate an embedding instead of a prompt completion
embedding: FALSE
